"""empty message

Revision ID: e13214b7db0b
Revises: 219157f190ed
Create Date: 2020-05-11 15:44:42.040982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e13214b7db0b'
down_revision = '219157f190ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('updated_on', sa.DateTime(), nullable=False))
    op.add_column('comments', sa.Column('created_on', sa.DateTime(), nullable=False))
    op.add_column('comments', sa.Column('updated_on', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'updated_on')
    op.drop_column('comments', 'created_on')
    op.drop_column('blogs', 'updated_on')
    # ### end Alembic commands ###
