"""empty message

Revision ID: e1764a1b17b4
Revises: 5cef677af7b4
Create Date: 2019-07-18 15:25:26.206765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1764a1b17b4'
down_revision = '5cef677af7b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
