version: '3'

services:

  frontend:
    container_name: blogboy_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - BlogBoy
    networks:
      - apinetwork

  BlogBoy:
    container_name: BlogBoy
    image: blogboy
    restart: always
    build: ./BlogBoy
    volumes: ['./BlogBoy:/BlogBoy']
    networks:
      - apinetwork
    expose:
      - "5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=blogboy
      - DB_USER=postgres
      - DB_PASS=hanu1729

  db:
    container_name: blogboy_db
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hanu1729
      - POSTGRES_DB=blogboy
    networks:
      - apinetwork
    volumes:
      - blogboy_db_data:/var/lib/postgresql/data

networks:
  apinetwork:

volumes:
  blogboy_db_data: