version: '3'

services:

  BlogBoy:
    container_name: BlogBoy
    image: blogboy
    restart: always
    build: ./BlogBoy
    volumes: ['./BlogBoy:/BlogBoy']
    networks:
      - apinetwork
    expose:
      - "5000"
    ports:
      - "5000:5000"

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    networks:
      - apinetwork
    expose:
      - "8080"
    ports:
      - "80:8080"
    tty: true

networks:
  apinetwork: