[program:app]
directory = /BlogBoy
command = gunicorn --bind 0.0.0.0:5000 manage:app --workers 3
autostart = true
autorestart = true
stopasgroup = true
killasgroup = true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopsignal = INT
stopwaitsecs = 3000